- name: Reboot_raspberry
  ansible.builtin.reboot:
    msg: "Raspberry boot config changed"
    connect_timeout: 5
    reboot_timeout: 300
  when: (ansible_facts.get('lsb', {}).get('id') == "Raspbian") or ("Raspberry Pi" in (ansible_facts.get('model') | default('', true)))
