- name: Ensure Nginx official APT repository
  ansible.builtin.import_tasks: apt_sources.yaml

- name: Install or upgrade Nginx package
  apt:
    name: nginx
    state: latest
  become: true

- name: Ensure openssl is installed
  apt:
    pkg: openssl
    state: latest
  become: true

- name: Deploy Nginx configuration and service
  ansible.builtin.import_tasks: configure.yaml
