- name: Ensure Nginx official APT repository
  ansible.builtin.import_tasks: apt_sources.yaml

- name: Update Nginx packages
  apt:
    name: nginx
    state: latest
    update_cache: false
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  notify: Restart nginx

- name: Deploy Nginx configuration and service
  ansible.builtin.import_tasks: configure.yaml
