- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Recreate WireGuard container
  # Equivalent to: docker compose up -d --force-recreate
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_env.HOME }}/.wg-easy"
    state: present
    remove_orphans: true
    build: "never"
    pull: "always"
    recreate: always
