- name: Get .bashrc file stat
  ansible.builtin.stat:
    path: "{{ user_home }}/.bashrc"
  register: bashrc

- name: Backup existing .bashrc if it exists
  ansible.builtin.copy:
    src: "{{ user_home }}/.bashrc"
    dest: "{{ user_home }}/.bashrc_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve
  when: bashrc.stat.exists

- name: Write .bashrc
  ansible.builtin.template:
    src: .bashrc.j2
    dest: "{{ user_home }}/.bashrc"
    mode: "u=rw,go=r"
