- name: Get .bashrc file stat
  ansible.builtin.stat:
    path: "{{ user_home }}/.bashrc"
  register: bash_bashrc

- name: Backup existing .bashrc if it exists
  ansible.builtin.copy:
    src: "{{ user_home }}/.bashrc"
    dest: "{{ user_home }}/.bashrc_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve
    remote_src: true
  when: bash_bashrc.stat.exists

- name: Write .bashrc
  ansible.builtin.template:
    src: .bashrc.j2
    dest: "{{ user_home }}/.bashrc"
    mode: u=rw,g=r,o=r # 644 (read and write access for the owner of the file and read access for group and others)
