- name: Deploy media websites
  block:
    - name: Backup existing vhost
      copy:
        src: "{{ nginx_conf_path }}/{{ item.domain }}.conf"
        dest: "{{ nginx_conf_path }}/{{ item.domain }}.conf.bak_{{ ansible_date_time.iso8601 }}"
        mode: preserve
      loop: "{{ websites_media }}"
      ignore_errors: true

    - name: Install Nginx vhost
      template:
        src: "vhosts/{{ item.domain }}.conf.j2"
        dest: "{{ nginx_conf_path }}/{{ item.domain }}.conf"
        mode: u=rw,g=r,o=r # 644
      loop: "{{ websites_media }}"

    - name: Enable vhost
      file:
        src: "{{ nginx_conf_path }}/{{ item.domain }}.conf"
        dest: "{{ nginx_enabled_path }}/{{ item.domain }}.conf"
        state: link
      loop: "{{ websites_media }}"
      notify: Reload nginx config
