- name: Reload nginx config
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Recreate dawarich stack
  community.docker.docker_compose_v2:
    project_src: "/opt/dawarich"
    state: present
    remove_orphans: true
    # TEMPORARY: build app image from git branch (revert to build: never, pull: always)
    build: "always"
    pull: "missing"
    recreate: always
