- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Create minecraft server directory
  file:
    path: "{{ user_home }}/minecraft-server"
    state: directory
    mode: "0755"

- name: Clone or update Minecraft server repository
  git:
    repo: "git@github.com:bolinocroustibat/minecraft-server.git"
    dest: "{{ user_home }}/minecraft-server"
    accept_hostkey: yes
    update: yes
    version: main
  register: git_clone

- name: Make minecraft-backup.sh executable
  file:
    path: "{{ user_home }}/minecraft-server/minecraft-backup.sh"
    mode: "0755"
  when: git_clone.changed

- name: Start Minecraft server
  docker_compose:
    project_src: "{{ user_home }}/minecraft-server"
    state: present
  register: output

- name: Add Minecraft backup cron job
  cron:
    name: "Minecraft server daily backup"
    minute: "0"
    hour: "4"
    job: "cd {{ user_home }}/minecraft-server && ./minecraft-backup.sh"
    user: root
    state: present
