galaxy_info:
  role_name: portainer
  author: bolino
  description: Role to install Portainer and Portainer Agent
  company: bolino
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - docker
    - portainer
    - container
    - monitoring

dependencies: []
