- name: Check if Oh-My-ZSH is installed
  ansible.builtin.stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: oh_my_zsh__installed

- name: Install Oh-My-ZSH
  when: not oh_my_zsh__installed.stat.exists
  block:
    - name: Create temporary file
      tempfile:
        state: file
      register: oh_my_zsh__install_script

    - name: Download Oh-My-ZSH installation script
      get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
        mode: u=rwx,g=rx,o=rx

    - name: Install Oh-My-ZSH installation script
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: oh_my_zsh_result
      failed_when: "'FAILED' in oh_my_zsh_result.stderr"
      changed_when: oh_my_zsh_result.find('The $ZSH folder already exists') == -1

    - name: Remove the temporary file
      file:
        path: /tmp/install_ohmyzsh.sh
        state: absent
      when: oh_my_zsh__install_script.path is defined

    - name: Clone zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "{{ user_home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
        version: master
        force: true

    - name: Clone zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: "{{ user_home }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
        version: master
        force: true

    - name: Install custom theme from template
      template:
        src: bolino.zsh-theme.j2
        dest: "{{ user_home }}/.oh-my-zsh/custom/themes/bolino.zsh-theme"
        mode: u=rw,g=r,o=r

- name: Backup existing .zshrc if it exists
  copy:
    remote_src: true
    src: "{{ user_home }}/.zshrc"
    dest: "{{ user_home }}/.zshrc_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Add oh-my-zsh config to .zshrc
  blockinfile:
    dest: "{{ user_home }}/.zshrc"
    block: "{{ lookup('template', '.zshrc.j2') }}"
    marker: "### {mark} Oh-My-Zsh (Ansible-managed) ### "
    mode: u=rw,g=r,o=r # 644 (read and write access for the owner of the file and read access for group and others)
