- name: Check if system is Debian-based
  when: ansible_distribution in ['Debian', 'Ubuntu']
  block:
    - name: Download rmate script
      get_url:
        url: https://raw.githubusercontent.com/aurora/rmate/master/rmate
        dest: /usr/local/bin/rmate
        mode: u=rwx,g=rx,o=rx
        validate_certs: yes
      register: download_result
      failed_when: download_result.status_code is defined and download_result.status_code != 200

    - name: Create symlink from rmate to sublime
      file:
        src: /usr/local/bin/rmate
        dest: /usr/local/bin/sublime
        state: link
        force: yes
      when: download_result is success
  rescue:
    - name: Report failure
      fail:
        msg: "Failed to setup rmate. Download status
