- name: Create ~/.ssh directory in user home
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=,o= # 700 (only the user can read, write and execute)

- name: Download SSH public key
  uri:
    url: http://adriencarpentier.com/id_ed25519.pub
    dest: "{{ user_home }}/.ssh/id_ed25519.pub"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw,g=,o= # 600 (only the user can read and write)
    validate_certs: true
    force: no  # Don't download if file exists

- name: Ensure authorized_keys file has correct permissions
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh/authorized_keys"
    state: file
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw,g=,o= # 600 (only the user can read and write)
    create: yes

- name: Add SSH public key to authorized_keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '{{ user_home }}/.ssh/id_ed25519.pub') }}"
    state: present
