- name: restart consul
  community.docker.docker_compose:
    project_src: "{{ consul_data_dir }}"
    state: present
    restarted: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded
