# Storage media disk configuration
storage_media__ssd_uuid: "918ffcee-cf26-4c57-96f7-80cac1fafbd2"
storage_media__mount_point: "/mnt/medias"
storage_media__owner: "debian-transmission"
storage_media__group: "debian-transmission"
