- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Set default policies
  community.general.ufw:
    default: "{{ item }}"
  loop:
    - deny
    - allow

- name: Allow SSH
  community.general.ufw:
    rule: allow
    name: ssh

- name: Allow Nginx HTTP and HTTPS
  community.general.ufw:
    rule: allow
    name: Nginx Full

- name: Enable UFW and persist across reboots
  community.general.ufw:
    state: enabled
    logging: 'on'
  register: ufw_enable

- name: Reload UFW
  community.general.ufw:
    state: reloaded
  when: ufw_enable.changed
