- name: Install Homebrew
  command: "/bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'"
  register: homebrew_brew_install_result
  changed_when: homebrew_brew_install_result.stdout.find("Homebrew is already installed") == -1
