- name: Restart owntracks
  community.docker.docker_compose_v2:
    project_src: "/opt/owntracks"
    state: present
    recreate: always

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
