- name: Include Portainer secrets
  include_vars: secrets.yaml

- name: Pull latest Portainer image
  community.docker.docker_image:
    name: portainer/portainer-ce:latest
    source: pull
    force_source: true
  register: portainer_image_result

- name: Recreate Portainer container with new image
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
      - "{{ portainer_web_port }}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  notify: Reload nginx config

- name: Clean up old Portainer images only
  shell: |
    # Get the current image ID being used by the container
    CURRENT_IMAGE=$(docker inspect portainer --format='{{.Image}}')

    # Remove all portainer images except the current one
    docker images portainer/portainer-ce --format "table {{.Repository}}:{{.Tag}}\t{{.ID}}" | grep -v "$CURRENT_IMAGE" | awk '{print $1}' | xargs -r docker rmi
  args:
    executable: /bin/bash
  ignore_errors: true
  when: portainer_image_result.changed
