
- name: Include Portainer secrets
  include_vars: secrets.yaml

- name: Update Portainer on data-bolino
  when: inventory_hostname == 'data-bolino'
  block:
    - name: Pull Portainer CE image
      community.docker.docker_image:
        name: "portainer/portainer-ce:{{ portainer_image_tag }}"
        source: pull
        force_source: true

    - name: Stop and remove existing Portainer container
      community.docker.docker_container:
        name: portainer
        state: absent
      ignore_errors: true

    - name: Recreate Portainer container with new image
      community.docker.docker_container:
        name: portainer
        image: "portainer/portainer-ce:{{ portainer_image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
          - "{{ portainer_web_port }}:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

- name: Update Portainer Agent on web-bolino
  when: inventory_hostname == 'web-bolino'
  block:
    - name: Pull Portainer Agent image
      community.docker.docker_image:
        name: "portainer/agent:{{ portainer_image_tag }}"
        source: pull
        force_source: true

    - name: Stop and remove existing Portainer Agent container
      community.docker.docker_container:
        name: portainer_agent
        state: absent
      ignore_errors: true

    - name: Recreate Portainer Agent container with new image
      community.docker.docker_container:
        name: portainer_agent
        image: "portainer/agent:{{ portainer_image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ portainer_agent_port }}:9001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_agent_data:/data
