- name: Include Portainer secrets
  include_vars: secrets.yaml

- name: Pull latest Portainer image only if needed
  community.docker.docker_image:
    name: portainer/portainer-ce:latest
    source: pull
    force_source: false
  register: portainer_image_result

- name: Recreate Portainer container with new image
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
      - "{{ portainer_web_port }}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  notify: Reload nginx config
  when: portainer_image_result.changed
