# For MacOS ("Darwin") systems, uv is updated as a Homebrew package.

- name: Update uv
  when: ansible_os_family == "Debian"
  command: "{{ uv_install_dir }}/uv self update"
  register: uv_result
  changed_when: "'on the latest version of uv' not in uv_result.stderr"
  failed_when: "'Err' in uv_result.msg"
