- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Add jail.local file
  template:
    src: jail.local.j2
    dest: "/etc/fail2ban/jail.local"
    owner: root
    group: root
    mode: u=rw,g=r,o=r # 644
  notify: restart fail2ban

- name: Add jail.d/* files
  template:
    src: "templates/jail.d/{{ item.name }}.conf"
    dest: "/etc/fail2ban/jail.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r # 644
  loop: "{{ fail2ban_jails }}"
  notify: restart fail2ban

- name: Add filter.d/* files
  template:
    src: "templates/filter.d/{{ item.name }}.conf"
    dest: "/etc/fail2ban/filter.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r # 644
  loop: "{{ fail2ban_filters }}"
  notify: restart fail2ban

- name: Enable fail2ban service
  service:
    name: fail2ban
    enabled: true
