- name: Install Micro text editor with homebrew
  homebrew:
    name: micro
    state: latest
  when: ansible_os_family == "Darwin"

- name: Install Micro text editor with apt
  apt:
    name: micro
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Ensure micro config directory exists
  file:
    path: "{{ user_home }}/.config/micro"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Backup existing config file if it exists
  copy:
    remote_src: true
    src: "{{ user_home }}/.config/micro/settings.json"
    dest: "{{ user_home }}/.config/micro/settings.json_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve
    owner: "{{ ansible_user }}"
  when: not ansible_check_mode and lookup('file', user_home + '/.config/micro/settings.json', errors='ignore') is defined

- name: Copy config file
  template:
    src: settings.json.j2
    dest: "{{ user_home }}/.config/micro/settings.json"
    mode: u=rw,g=r,o=r
