- name: Disable Wi-Fi in config.txt
  ansible.builtin.blockinfile:
    path: "{{ raspberry__config_path }}"
    block: |
      # Disable Wi-Fi (added by Ansible raspberry role)
      dtoverlay=disable-wifi
    marker: "# {mark} ANSIBLE raspberry disable-wifi"
    state: present
  become: true
  notify: Reboot Raspberry
  when: (ansible_facts.get('lsb', {}).get('id') == "Raspbian") or ("Raspberry Pi" in (ansible_facts.get('model') | default('', true)))

- name: Disable Bluetooth in config.txt
  ansible.builtin.blockinfile:
    path: "{{ raspberry__config_path }}"
    block: |
      # Disable Bluetooth (added by Ansible raspberry role)
      dtoverlay=disable-bt
    marker: "# {mark} ANSIBLE raspberry disable-bt"
    state: present
  become: true
  notify: Reboot Raspberry
  when: (ansible_facts.get('lsb', {}).get('id') == "Raspbian") or ("Raspberry Pi" in (ansible_facts.get('model') | default('', true)))

- name: Add Raspberry Pi kernel command line options
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: "^(?!.*(?:^| ){{ item | regex_escape }}(?: |$))(.*)$"
    line: '\1 {{ item }}'
    backrefs: true
  loop: "{{ raspberry__cmdline_options }}"
  become: true
  notify: Reboot Raspberry
  when:
    - (ansible_facts.get('lsb', {}).get('id') == "Raspbian") or ("Raspberry Pi" in (ansible_facts.get('model') | default('', true)))
    - raspberry__cmdline_options | length > 0
