
- name: Include Pi-hole secrets
  include_vars: secrets.yaml

- name: Ensure Pi-hole directory exists
  file:
    path: "/opt/pi-hole"
    state: directory
    mode: u=rwx,g=,o= # 700 (only the user can read, write and execute)

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/opt/pi-hole/docker-compose.yml"
    mode: u=rw,g=r,o=r # 644

- name: "Stop and remove existing Pi-hole container"
  community.docker.docker_container:
    name: pihole
    state: absent
  ignore_errors: true

- name: "Recreate Pi-hole container with new image"
  community.docker.docker_compose_v2:
    project_src: "/opt/pi-hole"
    state: present
    remove_orphans: true
    build: "never"
    pull: "always"
    recreate: always
