- name: Include Pi-hole secrets
  include_vars: secrets.yaml

- name: Pull latest Pi-hole image
  community.docker.docker_image:
    name: pihole/pihole:latest
    source: pull
    force_source: true

- name: Recreate Pi-hole container with new image
  community.docker.docker_compose_v2:
    project_src: "/opt/pi-hole"
    state: present
    remove_orphans: true
    build: "never"
    pull: "always"
    recreate: always
  notify: reload nginx
