- name: Install Starship
  block:
    - name: Install Starship with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: starship
        state: latest

    - name: Install Starship with curl
      when: ansible_os_family == "Debian"
      command: curl -fsSL https://starship.rs/install.sh | sh -s -- -y

- name: Backup existing starship.toml config file if it exists
  copy:
    remote_src: true
    src: "{{ user_home }}/.config/starship.toml"
    dest: "{{ user_home }}/.config/starship.toml_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Add starship.toml config file
  when: ansible_os_family == "Darwin"
  template:
    src: starship_local.toml
    dest: "{{ user_home }}/.config/starship.toml"
    mode: "u=rw,g=r,o=r" # 644 (read and write access for the owner of the file and read access for group and others)

- name: Add starship.toml config file
  when: ansible_os_family == "Debian"
  template:
    src: starship_remote.toml
    dest: "{{ user_home }}/.config/starship.toml"
    mode: "u=rw,g=r,o=r" # 644 (read and write access for the owner of the file and read access for group and others)

- name: Add Starship to .zshrc file
  blockinfile:
    dest: "{{ user_home }}/.zshrc"
    block: "{{ lookup('template', '.zshrc.j2') }}"
    marker: "### {mark} Starship (Ansible-managed) ### "
    mode: "u=rw,g=r,o=r" # 644 (read and write access for the owner of the file and read access for group and others)
