- name: Install Starship
  block:
    - name: Install Starship with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: starship
        state: present

    - name: Download Starship install script
      when: ansible_os_family == "Debian"
      get_url:
        url: "https://starship.rs/install.sh"
        dest: "/tmp/starship_install.sh"
        mode: u=rwx,g=rx,o=rx

    - name: Install Starship system-wide
      when: ansible_os_family == "Debian"
      command: "sh /tmp/starship_install.sh --bin-dir /usr/local/bin -y"

    - name: Delete Starship install script
      when: ansible_os_family == "Debian"
      file:
        path: "/tmp/starship_install.sh"
        state: absent

- name: Get list of users
  getent:
    database: passwd
  register: starship_users

- name: Configure Starship for users
  include_tasks: configure_user.yaml
  loop:
    - { home: "/root", user: "root" }
    - { home: "/home/github", user: "github" }
  loop_control:
    loop_var: user_config
  when: user_config.user in starship_users.ansible_facts.getent_passwd.keys()
