---
- name: Install Docker on web-bolino
  hosts: web-bolino
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create Docker GPG key directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Create Docker sources file
      copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: {{ debian_version }}
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Update apt cache after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Verify Docker installation
      command: docker run hello-world
      register: docker_hello
      changed_when: false
      failed_when: false

    - name: Display Docker verification result
      debug:
        msg: "{{ docker_hello.stdout_lines + docker_hello.stderr_lines }}"

    - name: Check Docker service status
      command: systemctl status docker
      register: docker_status
      changed_when: false
      failed_when: false

    - name: Display Docker service status
      debug:
        msg: "{{ docker_status.stdout_lines }}"
