- name: Prune Docker images and containers
  hosts: web-bolino,data-bolino,pi-bolino
  tasks:
    - name: Include Docker prune tasks
      include_role:
        name: docker
        tasks_from: prune
