- name: Update Docker-based services on data-bolino
  hosts: data-bolino
  tags:
    - debian
  tasks:
    - name: Include nginx role for handlers
      include_role:
        name: nginx
        tasks_from: install

    - name: Update OmniTools
      include_role:
        name: omnitools
        tasks_from: update

    - name: Update Pi-hole
      include_role:
        name: pi-hole
        tasks_from: update

    - name: Update Uptime Kuma
      include_role:
        name: uptime_kuma
        tasks_from: update

    - name: Update WireGuard
      include_role:
        name: wg_easy
        tasks_from: update

- name: Update Portainer
  hosts: remote
  tags:
    - debian
  tasks:
    - name: Include nginx role for handlers
      include_role:
        name: nginx
        tasks_from: install

    - name: Update Portainer
      include_role:
        name: portainer
        tasks_from: update

- name: Prune Docker resources
  hosts: remote
  tags:
    - debian
  tasks:
    - name: Prune unused Docker resources
      include_role:
        name: docker
        tasks_from: prune
