- name: Update Homebrew and upgrade packages
  hosts: local
  tasks:
    - name: Update Homebrew packages
      include_role:
        name: homebrew
        tasks_from: upgrade

- name: Update apt and upgrade packages
  hosts: remote
  tasks:
    - name: Upgrade apt packages
      include_role:
        name: apt
        tasks_from: upgrade

- name: Update ZSH and plugins
  hosts: all
  tasks:
    - name: Update ZSH
      include_role:
        name: zsh
        tasks_from: update

- name: Update Starship
  hosts: remote
  tasks:
    - name: Update Starship prompt
      include_role:
        name: starship
        tasks_from: update

- name: Update global pip
  hosts: remote # python is entirely managed by uv on local
  tasks:
    - name: Update pip packages
      include_role:
        name: pip
        tasks_from: update
      ignore_errors: true # pip may be managed by uv, so we don't want to fail if it is

- name: Update fail2ban configurations
  hosts: remote
  tags: fail2ban
  tasks:
    - name: Update fail2ban configurations
      include_role:
        name: fail2ban
        tasks_from: update

- name: Update uv
  hosts: all
  tasks:
    - name: Update uv package manager
      include_role:
        name: uv
        tasks_from: update
