- name: Update Bun via Homebrew (MacOS)
  community.general.homebrew:
    name: bun
    state: latest
  become: false
  when: ansible_os_family == "Darwin"

- name: Check if Bun is installed (Debian)
  command: which bun
  register: bun_location
  changed_when: false
  become: false
  when: ansible_os_family == "Debian"
  ignore_errors: true

- name: Upgrade Bun (Debian)
  command: bun upgrade
  register: bun_upgrade
  changed_when: "'Already up to date' not in bun_upgrade.stdout"
  become: false
  when:
    - ansible_os_family == "Debian"
    - bun_location.rc == 0
