- name: Get image version from running container
  command: docker exec wg-easy cat /app/package.json
  register: wg_package
  ignore_errors: true

- name: Extract version
  set_fact:
    wg_version: "{{ (wg_package.stdout | from_json).version }}"
  when: wg_package.rc == 0

- name: Show current WireGuard version
  debug:
    msg: "WireGuard is running version {{ wg_version | default('unknown') }}"

- name: Include WireGuard secrets
  include_vars: secrets.yaml

- name: Ensure WireGuard directory exists
  file:
    path: "/opt/wg-easy"
    state: directory
    mode: u=rwx,g=,o= # 700 (only the user can read, write and execute)

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/opt/wg-easy/docker-compose.yml"
    mode: u=rw,g=r,o=r # 644

- name: Pull latest wg-easy image
  community.docker.docker_image:
    name: ghcr.io/wg-easy/wg-easy:latest
    source: pull
    force_source: true
  register: wg_easy_image_result

- name: Get version from latest pulled image
  command: docker run --rm ghcr.io/wg-easy/wg-easy:latest cat /app/package.json
  register: latest_package
  when: wg_easy_image_result.changed

- name: Extract latest version
  set_fact:
    latest_version: "{{ (latest_package.stdout | from_json).version }}"
  when: wg_easy_image_result.changed and latest_package.rc == 0

- name: Show latest WireGuard version
  debug:
    msg: "Latest WireGuard version: {{ latest_version | default('unknown') }} (updating from {{ wg_version | default('unknown') }})"
  when: wg_easy_image_result.changed

- name: "Stop and remove existing wg-easy container (updating to {{ latest_version | default('latest') }})"
  community.docker.docker_container:
    name: wg-easy
    state: absent
  ignore_errors: true
  when: wg_easy_image_result.changed

- name: "Recreate WireGuard container with new image (version {{ latest_version | default('latest') }})"
  community.docker.docker_compose_v2:
    project_src: "/opt/wg-easy"
    state: present
    remove_orphans: true
    build: "never"
    pull: "always"
    recreate: always
  notify: Reload nginx config
  when: wg_easy_image_result.changed

- name: "Clean up old wg-easy images (keeping version {{ latest_version | default('latest') }})"
  shell: |
    # Get the current image ID being used by the container
    CURRENT_IMAGE=$(docker inspect wg-easy --format="{{.Image}}")

    # Remove all wg-easy images except the current one
    docker images ghcr.io/wg-easy/wg-easy --format "table {{.Repository}}:{{.Tag}}\t{{.ID}}" | grep -v "$CURRENT_IMAGE" | awk '{print $1}' | xargs -r docker rmi
  args:
    executable: /bin/bash
  ignore_errors: true
  when: wg_easy_image_result.changed
