- name: Include WireGuard secrets
  include_vars: secrets.yaml

- name: Pull latest wg-easy image
  community.docker.docker_image:
    name: ghcr.io/wg-easy/wg-easy:latest
    source: pull
    force_source: true

- name: Recreate WireGuard container with new image
  community.docker.docker_compose_v2:
    project_src: "/opt/wg-easy"
    state: present
    remove_orphans: true
    build: "never"
    pull: "always"
    recreate: always
  notify: reload nginx
